spring.application.name=authapi

# === PostgreSQL Configuration ===
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=auth


# === JPA Configuration ===
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# === Flyway configuration ===
spring.flyway.enabled=true
spring.flyway.locations=db/migration
spring.flyway.out-of-order=false
spring.flyway.schemas=auth

loggind.level.org.springframework.security=DEBUG

# === JWT configuration ===
api.security.token.secret=${JWT_TOKEN}
